
import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font'
import Navbar from '@/components/navbar/navbar'

export const metadata: Metadata = {
  title: "ecopontos",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Navbar></Navbar>

        {children}</body>
    </html>
  )
}
